#### Load Data

In [1]:
# Load JSON data into a dataframe
import pandas as pd
import json


def load_data():
    with open(r'..\data\scrape_results\dashen\review_dashen_bank_scrape_result.json', 'r', encoding='utf-8') as dashed_data:
        dashen_json = json.load(dashed_data)
        df_dashen = pd.DataFrame(dashen_json)
    with open(r'..\data\scrape_results\boa\review_boa_bank_scrape_result.json', 'r', encoding='utf-8') as boa_data:
        boa_json = json.load(boa_data)
        df_boa = pd.DataFrame(boa_json)
    with open(r'..\data\scrape_results\cbe\review_cbe_bank_scrape_result.json', 'r', encoding='utf-8') as cbe_data:
        cbe_json = json.load(cbe_data)
        df_cbe = pd.DataFrame(cbe_json)
    return df_dashen, df_boa, df_cbe

df_dashen, df_boa, df_cbe = load_data()

In [15]:
df_dashen.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,22818807-3368-446c-8a3b-d3ca2e07a2d8,OBSA KA,https://play-lh.googleusercontent.com/a-/ALV-U...,love,3,0,1.0.16,2025-06-06 00:15:44,None,None,1.0.16
1,6ece1f5e-55f2-404d-b980-1cb45823180f,Masersha,https://play-lh.googleusercontent.com/a/ACg8oc...,መቸሸጠ,5,0,1.0.16,2025-06-03 19:40:31,None,None,1.0.16
2,765ff69f-5274-45c5-985b-81b8d01e1874,Koki Mulugeta,https://play-lh.googleusercontent.com/a/ACg8oc...,wow,5,0,None,2025-06-03 17:30:11,None,None,None
3,7db66b6a-a044-43f1-a7ad-ea8a10815548,Badhasa Dassaalany,https://play-lh.googleusercontent.com/a/ACg8oc...,gadaa,5,0,1.0.16,2025-06-01 17:10:53,None,None,1.0.16
4,caf4a80c-85db-4b49-ab9c-a0b55e152317,Nebiyu Getachew Mamo,https://play-lh.googleusercontent.com/a-/ALV-U...,Massive upgrade from the Amole app.,5,0,1.0.16,2025-05-31 23:04:04,None,None,1.0.16

In [27]:
df_boa.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,937102c6-ae88-419c-994b-80e520faacb8,Phillmon Haftom,https://play-lh.googleusercontent.com/a/ACg8oc...,it's not working,3,0,25.05.03,2025-06-05 11:57:36,None,None,25.05.03
1,3559b91c-fad9-4032-bebe-cf99974b9628,Robel Alebachew,https://play-lh.googleusercontent.com/a/ACg8oc...,"Hello, I’m facing a problem with the BOA Mobil...",1,0,None,2025-06-03 16:21:34,None,None,None
2,10e85f30-540d-4810-ba89-85a7e004480b,Haymanot Anberber,https://play-lh.googleusercontent.com/a/ACg8oc...,exceptional,5,0,None,2025-06-03 10:32:35,None,None,None
3,d7f07898-4ba1-47b4-9e8c-a3cc10b1bf0f,Mohamed Abdillahi,https://play-lh.googleusercontent.com/a-/ALV-U...,BoA Mobile good bank,5,0,25.05.03,2025-06-02 14:25:12,None,None,25.05.03
4,2ca9480b-ff5f-4b59-952c-5921db83dab2,Ahadu tech,https://play-lh.googleusercontent.com/a-/ALV-U...,this is worest app 24/7 loading,1,0,25.05.03,2025-06-01 15:51:10,None,None,25.05.03

In [16]:
df_cbe.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,be2cb2ac-bbe0-4175-81c4-9f6c86afdaaa,Aim4 Beyond,https://play-lh.googleusercontent.com/a/ACg8oc...,"""Why don’t your ATMs support account-to-accoun...",4,0,None,2025-06-06 09:54:11,None,None,None
1,8efd71e9-59cd-41ce-8c5c-12052dee9ad0,zakir man,https://play-lh.googleusercontent.com/a/ACg8oc...,what is this app problem???,1,0,5.1.0,2025-06-05 22:16:56,None,None,5.1.0
2,b12d0383-9b27-4e49-a94d-277a43b15800,Yesuf Ahmed,https://play-lh.googleusercontent.com/a/ACg8oc...,the app is proactive and a good connections.,5,0,5.1.0,2025-06-05 15:55:10,None,None,5.1.0
3,dd9f9e37-177a-46df-b877-d0edaa9aed29,Yonas Mekonnen,https://play-lh.googleusercontent.com/a-/ALV-U...,I cannot send to cbebirr app. through this app.,3,0,None,2025-06-05 11:12:49,None,None,None
4,8e34703c-203c-4180-8b32-bfd0b3f0c871,Yibrah Yebo,https://play-lh.googleusercontent.com/a/ACg8oc...,good,4,0,None,2025-06-05 10:21:59,None,None,None

In [17]:
def get_info():
    print("------------------------------------")
    print("CBE BANK INFO")
    df_cbe.info()
    print("------------------------------------")
    print("BOA BANK INFO")
    df_boa.info()
    print("------------------------------------")
    print("DASHEN BANK INFO")
    df_dashen.info()

get_info()

------------------------------------
CBE BANK INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7498 entries, 0 to 7497
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              7498 non-null   object
 1   userName              7498 non-null   object
 2   userImage             7498 non-null   object
 3   content               7491 non-null   object
 4   score                 7498 non-null   int64
 5   thumbsUpCount         7498 non-null   int64
 6   reviewCreatedVersion  6152 non-null   object
 7   at                    7498 non-null   object
 8   replyContent          47 non-null     object
 9   repliedAt             47 non-null     object
 10  appVersion            6152 non-null   object
dtypes: int64(2), object(9)
memory usage: 644.5+ KB
------------------------------------
BOA BANK INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1045 entries, 0 to 1044
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              1045 non-null   object
 1   userName              1045 non-null   object
 2   userImage             1045 non-null   object
 3   content               1045 non-null   object
 4   score                 1045 non-null   int64
 5   thumbsUpCount         1045 non-null   int64
 6   reviewCreatedVersion  754 non-null    object
 7   at                    1045 non-null   object
 8   replyContent          23 non-null     object
 9   repliedAt             23 non-null     object
 10  appVersion            754 non-null    object
dtypes: int64(2), object(9)
memory usage: 89.9+ KB
------------------------------------
DASHEN BANK INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 448 entries, 0 to 447
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              448 non-null    object
 1   userName              448 non-null    object
 2   userImage             448 non-null    object
 3   content               448 non-null    object
 4   score                 448 non-null    int64
 5   thumbsUpCount         448 non-null    int64
 6   reviewCreatedVersion  357 non-null    object
 7   at                    448 non-null    object
 8   replyContent          0 non-null      object
 9   repliedAt             0 non-null      object
 10  appVersion            357 non-null    object
dtypes: int64(2), object(9)
memory usage: 38.6+ KB

In [ ]:
def null_percentage(df):
    number_of_rows, number_of_columns = df.shape
    df_size = number_of_rows * number_of_columns
    
    null_size = (df.isnull().sum()).sum()
    percentage = round((null_size / df_size) * 100, 2)
    return f"Data Frame contain total null values of { percentage }%"

def calculate_total_null_values():
    print("------------------------------------")
    print("CBE BANK NULL VALUES")
    result = null_percentage(df_cbe)
    print(f"CBE dataframe: {result}")
    print("------------------------------------")
    print("BOA BANK NULL VALUES")
    result = null_percentage(df_boa)
    print(f"BOA dataframe: {result}")
    print("------------------------------------")
    print("DASHEN BANK NULL VALUES")
    result = null_percentage(df_dashen)
    print(f"DASHEN dataframe: {result}")
calculate_total_null_values()

In [21]:
def missing_values_per_column(df):
    return df.isnull().sum()

def calculate_missing_values_per_column():
    print("------------------------------------")
    print("CBE BANK COLUMN MISSING VALUES")
    result = missing_values_per_column(df_cbe)
    print(f"CBE dataframe: {result}")
    print("------------------------------------")
    print("BOA BANK COLUMN MISSING VALUES")
    result = missing_values_per_column(df_boa)
    print(f"BOA dataframe: {result}")
    print("------------------------------------")
    print("DASHEN BANK COLUMN MISSING VALUES")
    result = missing_values_per_column(df_dashen)
    print(f"DASHEN dataframe: {result}")

calculate_missing_values_per_column()

------------------------------------
CBE BANK COLUMN MISSING VALUES
CBE dataframe: reviewId                   0
userName                   0
userImage                  0
content                    7
score                      0
thumbsUpCount              0
reviewCreatedVersion    1346
at                         0
replyContent            7451
repliedAt               7451
appVersion              1346
dtype: int64
------------------------------------
BOA BANK COLUMN MISSING VALUES
BOA dataframe: reviewId                   0
userName                   0
userImage                  0
content                    0
score                      0
thumbsUpCount              0
reviewCreatedVersion     291
at                         0
replyContent            1022
repliedAt               1022
appVersion               291
dtype: int64
------------------------------------
DASHEN BANK COLUMN MISSING VALUES
DASHEN dataframe: reviewId                  0
userName                  0
userImage                 0
content                   0
score                     0
thumbsUpCount             0
reviewCreatedVersion     91
at                        0
replyContent            448
repliedAt               448
appVersion               91
dtype: int64

As can be seen from the above output, most missing values are concentrated on columns
replyContent
repliedAt
appVersion

Hence we will remove these columns and recalculate the missing values percentage and check
if its less than 5%

#### Dropping columns with high numer of missing values

In [2]:
df_cbe = df_cbe.drop(['replyContent', 'repliedAt', 'appVersion'], axis=1)
df_boa = df_boa.drop(['replyContent', 'repliedAt', 'appVersion'], axis=1)
df_dashen = df_dashen.drop(['replyContent', 'repliedAt', 'appVersion'], axis=1)

#### Re-calculating total null values

In [5]:
calculate_total_null_values()

------------------------------------
CBE BANK NULL VALUES
CBE dataframe: Data Frame contain total null values of 2.26%
------------------------------------
BOA BANK NULL VALUES
BOA dataframe: Data Frame contain total null values of 3.48%
------------------------------------
DASHEN BANK NULL VALUES
DASHEN dataframe: Data Frame contain total null values of 2.54%

#### Check for duplicates

In [29]:
def check_for_duplicates(df):
    duplicates_df = df[df.duplicated()]
    return duplicates_df

def check_duplicates_for_all_banks():
    print("------------------------------------")
    print("CBE BANK DUPLICATES")
    result = check_for_duplicates(df_cbe)
    print(f"CBE duplicates dataframe: {result}")
    print("------------------------------------")
    print("BOA BANK DUPLICATES")
    result = check_for_duplicates(df_boa)
    print(f"BOA duplicates dataframe: {result}")
    print("------------------------------------")
    print("DASHEN BANK DUPLICATES")
    result = check_for_duplicates(df_dashen)
    print(f"DASHEN duplicates dataframe: {result}")

check_duplicates_for_all_banks()

------------------------------------
CBE BANK DUPLICATES
CBE duplicates dataframe: Empty DataFrame
Columns: [reviewId, userName, userImage, content, score, thumbsUpCount, reviewCreatedVersion, at]
Index: []
------------------------------------
BOA BANK DUPLICATES
BOA duplicates dataframe: Empty DataFrame
Columns: [reviewId, userName, userImage, content, score, thumbsUpCount, reviewCreatedVersion, at]
Index: []
------------------------------------
DASHEN BANK DUPLICATES
DASHEN duplicates dataframe: Empty DataFrame
Columns: [reviewId, userName, userImage, content, score, thumbsUpCount, reviewCreatedVersion, at]
Index: []

In [ ]:
def normalize_date(df):
    # Convert 'at' column to datetime object
    df['at'] = pd.to_datetime(df['at'], errors='coerce')
    df['created_at_date'] = df['at'].dt.normalize()

def normalize_dates_for_all_banks():
    normalize_date(df_cbe)
    normalize_date(df_boa)
    normalize_date(df_dashen)

normalize_dates_for_all_banks()

------------------------------------
CBE BANK
------------------------------------
BOA BANK
------------------------------------
DASHEN BANK

In [16]:
print("------------------------------------")
print("CBE BANK")
df_cbe.head()

------------------------------------
CBE BANK

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,created_at_date
0,be2cb2ac-bbe0-4175-81c4-9f6c86afdaaa,Aim4 Beyond,https://play-lh.googleusercontent.com/a/ACg8oc...,"""Why don’t your ATMs support account-to-accoun...",4,0,None,2025-06-06 09:54:11,2025-06-06
1,8efd71e9-59cd-41ce-8c5c-12052dee9ad0,zakir man,https://play-lh.googleusercontent.com/a/ACg8oc...,what is this app problem???,1,0,5.1.0,2025-06-05 22:16:56,2025-06-05
2,b12d0383-9b27-4e49-a94d-277a43b15800,Yesuf Ahmed,https://play-lh.googleusercontent.com/a/ACg8oc...,the app is proactive and a good connections.,5,0,5.1.0,2025-06-05 15:55:10,2025-06-05
3,dd9f9e37-177a-46df-b877-d0edaa9aed29,Yonas Mekonnen,https://play-lh.googleusercontent.com/a-/ALV-U...,I cannot send to cbebirr app. through this app.,3,0,None,2025-06-05 11:12:49,2025-06-05
4,8e34703c-203c-4180-8b32-bfd0b3f0c871,Yibrah Yebo,https://play-lh.googleusercontent.com/a/ACg8oc...,good,4,0,None,2025-06-05 10:21:59,2025-06-05

In [15]:
print("------------------------------------")
print("BOA BANK")
df_boa.head()

------------------------------------
BOA BANK

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,created_at_date
0,937102c6-ae88-419c-994b-80e520faacb8,Phillmon Haftom,https://play-lh.googleusercontent.com/a/ACg8oc...,it's not working,3,0,25.05.03,2025-06-05 11:57:36,2025-06-05
1,3559b91c-fad9-4032-bebe-cf99974b9628,Robel Alebachew,https://play-lh.googleusercontent.com/a/ACg8oc...,"Hello, I’m facing a problem with the BOA Mobil...",1,0,None,2025-06-03 16:21:34,2025-06-03
2,10e85f30-540d-4810-ba89-85a7e004480b,Haymanot Anberber,https://play-lh.googleusercontent.com/a/ACg8oc...,exceptional,5,0,None,2025-06-03 10:32:35,2025-06-03
3,d7f07898-4ba1-47b4-9e8c-a3cc10b1bf0f,Mohamed Abdillahi,https://play-lh.googleusercontent.com/a-/ALV-U...,BoA Mobile good bank,5,0,25.05.03,2025-06-02 14:25:12,2025-06-02
4,2ca9480b-ff5f-4b59-952c-5921db83dab2,Ahadu tech,https://play-lh.googleusercontent.com/a-/ALV-U...,this is worest app 24/7 loading,1,0,25.05.03,2025-06-01 15:51:10,2025-06-01

In [17]:
print("------------------------------------")
print("DASHEN BANK")
df_dashen.head()

------------------------------------
DASHEN BANK

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,created_at_date
0,22818807-3368-446c-8a3b-d3ca2e07a2d8,OBSA KA,https://play-lh.googleusercontent.com/a-/ALV-U...,love,3,0,1.0.16,2025-06-06 00:15:44,2025-06-06
1,6ece1f5e-55f2-404d-b980-1cb45823180f,Masersha,https://play-lh.googleusercontent.com/a/ACg8oc...,መቸሸጠ,5,0,1.0.16,2025-06-03 19:40:31,2025-06-03
2,765ff69f-5274-45c5-985b-81b8d01e1874,Koki Mulugeta,https://play-lh.googleusercontent.com/a/ACg8oc...,wow,5,0,None,2025-06-03 17:30:11,2025-06-03
3,7db66b6a-a044-43f1-a7ad-ea8a10815548,Badhasa Dassaalany,https://play-lh.googleusercontent.com/a/ACg8oc...,gadaa,5,0,1.0.16,2025-06-01 17:10:53,2025-06-01
4,caf4a80c-85db-4b49-ab9c-a0b55e152317,Nebiyu Getachew Mamo,https://play-lh.googleusercontent.com/a-/ALV-U...,Massive upgrade from the Amole app.,5,0,1.0.16,2025-05-31 23:04:04,2025-05-31

In [20]:
def add_bank_and_source(df, bank, source):
    df['bank'] = bank
    df['source'] = source

def add_bank_and_source_for_all_banks():
    print("------------------------------------")
    print("CBE BANK")
    add_bank_and_source(df_cbe, 'cbe', 'playstore')
    df_cbe.info()
    print("------------------------------------")
    print("BOA BANK")
    add_bank_and_source(df_boa, 'boa', 'playstore')
    df_boa.info()
    print("------------------------------------")
    print("DASHEN BANK")   
    add_bank_and_source(df_dashen, 'dashen', 'playstore')
    df_dashen.info()

add_bank_and_source_for_all_banks()

------------------------------------
CBE BANK
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7498 entries, 0 to 7497
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              7498 non-null   object
 1   userName              7498 non-null   object
 2   userImage             7498 non-null   object
 3   content               7491 non-null   object
 4   score                 7498 non-null   int64
 5   thumbsUpCount         7498 non-null   int64
 6   reviewCreatedVersion  6152 non-null   object
 7   at                    7498 non-null   datetime64[ns]
 8   created_at_date       7498 non-null   datetime64[ns]
 9   bank                  7498 non-null   object
 10  source                7498 non-null   object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 644.5+ KB
------------------------------------
BOA BANK
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1045 entries, 0 to 1044
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              1045 non-null   object
 1   userName              1045 non-null   object
 2   userImage             1045 non-null   object
 3   content               1045 non-null   object
 4   score                 1045 non-null   int64
 5   thumbsUpCount         1045 non-null   int64
 6   reviewCreatedVersion  754 non-null    object
 7   at                    1045 non-null   datetime64[ns]
 8   created_at_date       1045 non-null   datetime64[ns]
 9   bank                  1045 non-null   object
 10  source                1045 non-null   object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 89.9+ KB
------------------------------------
DASHEN BANK
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 448 entries, 0 to 447
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              448 non-null    object
 1   userName              448 non-null    object
 2   userImage             448 non-null    object
 3   content               448 non-null    object
 4   score                 448 non-null    int64
 5   thumbsUpCount         448 non-null    int64
 6   reviewCreatedVersion  357 non-null    object
 7   at                    448 non-null    datetime64[ns]
 8   created_at_date       448 non-null    datetime64[ns]
 9   bank                  448 non-null    object
 10  source                448 non-null    object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 38.6+ KB

In [21]:
print("CBE BANK")
df_cbe.head(1)

CBE BANK

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,created_at_date,bank,source
0,be2cb2ac-bbe0-4175-81c4-9f6c86afdaaa,Aim4 Beyond,https://play-lh.googleusercontent.com/a/ACg8oc...,"""Why don’t your ATMs support account-to-accoun...",4,0,None,2025-06-06 09:54:11,2025-06-06,cbe,playstore

In [22]:
print("BOA BANK")
df_boa.head(1)

BOA BANK

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,created_at_date,bank,source
0,937102c6-ae88-419c-994b-80e520faacb8,Phillmon Haftom,https://play-lh.googleusercontent.com/a/ACg8oc...,it's not working,3,0,25.05.03,2025-06-05 11:57:36,2025-06-05,boa,playstore

In [23]:
print("DASHEN BANK")
df_dashen.head(1)

DASHEN BANK

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,created_at_date,bank,source
0,22818807-3368-446c-8a3b-d3ca2e07a2d8,OBSA KA,https://play-lh.googleusercontent.com/a-/ALV-U...,love,3,0,1.0.16,2025-06-06 00:15:44,2025-06-06,dashen,playstore